--love, friendly, neutral, mistrust, dislike, hate
-- factions[npc_map[y][x].a_type][iterator][dis
factions = {
   ["Human"] = { --human?    
      {"Human", "friendly"}, --1
      {"Half Elf", "neutral"}, --2
      {"Norlander", "mistrust"}, --3...
      {"Nomad", "mistrust"},
      {"Elf", "mistrust"},
      {"Dark Elf", "dislike"},
      {"High Elf", "neutral"},
      {"Gnome", "friendly"},
      {"Dwarf", "neutral"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "friendly"},
      {"Wild Elf", "mistrust"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "dislike"},
      {"Catman", "dislike"},
      {"Ratigan", "hate"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["HalfElf"] = { -- factions.human[1][1]
      {"Human", "friendly"},
      {"HalfElf", "neutral"},
      {"Norlander", "mistrust"},
      {"Nomad", "mistrust"},
      {"Elf", "friendly"},
      {"Dark Elf", "neutral"},
      {"High Elf", "love"},
      {"Gnome", "neutral"},
      {"Dwarf", "neutral"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "friendly"},
      {"Wild Elf", "mistrust"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "dislike"},
      {"Catman", "dislike"},
      {"Ratigan", "hate"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Norlander"] = { 
      {"Human", "neutral"},
      {"HalfElf", "mistrust"},
      {"Norlander", "friendly"},
      {"Nomad", "neutral"},
      {"Elf", "dislike"},
      {"Dark Elf", "hate"},
      {"High Elf", "dislike"},
      {"Gnome", "neutral"},
      {"Dwarf", "neutral"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "neutral"},
      {"Wild Elf", "mistrust"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "neutral"},
      {"Catman", "dislike"},
      {"Ratigan", "hate"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Nomad"] = { 
      {"Human", "neutral"},
      {"HalfElf", "neutral"},
      {"Norlander", "neutral"},
      {"Nomad", "friendly"},
      {"Elf", "neutral"},
      {"Dark Elf", "dislike"},
      {"High Elf", "neutral"},
      {"Gnome", "dislike"},
      {"Dwarf", "dislike"},
      {"Abyss Dwarf", "neutral"},
      {"Topside Dwarf", "neutral"},
      {"Wild Elf", "neutral"},
      {"Goblin", "dislike"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "neutral"},
      {"Catman", "neutral"},
      {"Ratigan", "dislike"},
      {"Mermen", "friendly"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "dislike"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Elf"] = { 
      {"Human", "neutral"},
      {"HalfElf", "neutral"},
      {"Norlander", "neutral"},
      {"Nomad", "neutral"},
      {"Elf", "friendly"},
      {"Dark Elf", "hate"},
      {"High Elf", "friendly"},
      {"Gnome", "friendly"},
      {"Dwarf", "dislike"},
      {"Abyss Dwarf", "dislike"},
      {"Topside Dwarf", "dislike"},
      {"Wild Elf", "friendly"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "neutral"},
      {"Catman", "neutral"},
      {"Ratigan", "neutral"},
      {"Mermen", "friendly"},
      {"Harepon", "dislike"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Dark Elf"] = { 
      {"Human", "dislike"},
      {"HalfElf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "dislike"},
      {"Elf", "hate"},
      {"Dark Elf", "neutral"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "dislike"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "mistrust"},
      {"Orc", "mistrust"},
      {"Trorc", "neutral"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "mistrust"},
      {"Mermen", "hate"},
      {"Harepon", "dislike"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["High Elf"] = { 
      {"Human", "neutral"},
      {"HalfElf", "neutral"},
      {"Norlander", "neutral"},
      {"Nomad", "neutral"},
      {"Elf", "friendly"},
      {"Dark Elf", "hate"},
      {"High Elf", "friendly"},
      {"Gnome", "friendly"},
      {"Dwarf", "dislike"},
      {"Abyss Dwarf", "dislike"},
      {"Topside Dwarf", "dislike"},
      {"Wild Elf", "friendly"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "neutral"},
      {"Catman", "neutral"},
      {"Ratigan", "neutral"},
      {"Mermen", "friendly"},
      {"Harepon", "dislike"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Gnome"] = { 
      {"Human", "friendly"},
      {"HalfElf", "friendly"},
      {"Norlander", "friendly"},
      {"Nomad", "friendly"},
      {"Elf", "friendly"},
      {"Dark Elf", "hate"},
      {"High Elf", "friendly"},
      {"Gnome", "friendly"},
      {"Dwarf", "friendly"},
      {"Abyss Dwarf", "friendly"},
      {"Topside Dwarf", "friendly"},
      {"Wild Elf", "neutral"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "neutral"},
      {"Catman", "neutral"},
      {"Ratigan", "neutral"},
      {"Mermen", "friendly"},
      {"Harepon", "dislike"},
      {"Locustin", "dislike"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Dwarf"] = { --human?    
      {"Human", "neutral"},
      {"Half Elf", "neutral"},
      {"Norlander", "neutral"},
      {"Nomad", "mistrust"},
      {"Elf", "mistrust"},
      {"Dark Elf", "hate"},
      {"High Elf", "mistrust"},
      {"Gnome", "friendly"},
      {"Dwarf", "friendly"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "friendly"},
      {"Wild Elf", "mistrust"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "mistrust"},
      {"Catman", "mistrust"},
      {"Ratigan", "mistrust"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Dwarf"] = {    
      {"Human", "neutral"},
      {"Half Elf", "neutral"},
      {"Norlander", "neutral"},
      {"Nomad", "mistrust"},
      {"Elf", "mistrust"},
      {"Dark Elf", "hate"},
      {"High Elf", "mistrust"},
      {"Gnome", "friendly"},
      {"Dwarf", "friendly"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "friendly"},
      {"Wild Elf", "mistrust"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "mistrust"},
      {"Catman", "mistrust"},
      {"Ratigan", "mistrust"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Abyss Dwarf"] = {    
      {"Human", "mistrust"},
      {"Half Elf", "mistrust"},
      {"Norlander", "mistrust"},
      {"Nomad", "neutral"},
      {"Elf", "mistrust"},
      {"Dark Elf", "neutral"},
      {"High Elf", "mistrust"},
      {"Gnome", "mistrust"},
      {"Dwarf", "neutral"},
      {"Abyss Dwarf", "friendly"},
      {"Topside Dwarf", "friendly"},
      {"Wild Elf", "mistrust"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "mistrust"},
      {"Catman", "mistrust"},
      {"Ratigan", "mistrust"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Topside Dwarf"] = {    
      {"Human", "friendly"},
      {"Half Elf", "friendly"},
      {"Norlander", "neutral"},
      {"Nomad", "neutral"},
      {"Elf", "neutral"},
      {"Dark Elf", "hate"},
      {"High Elf", "mistrust"},
      {"Gnome", "friendly"},
      {"Dwarf", "friendly"},
      {"Abyss Dwarf", "friendly"},
      {"Topside Dwarf", "neutral"},
      {"Wild Elf", "neutral"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "mistrust"},
      {"Catman", "mistrust"},
      {"Ratigan", "mistrust"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Wild Elf"] = {    
      {"Human", "mistrust"},
      {"Half Elf", "neutral"},
      {"Norlander", "neutral"},
      {"Nomad", "neutral"},
      {"Elf", "neutral"},
      {"Dark Elf", "hate"},
      {"High Elf", "mistrust"},
      {"Gnome", "friendly"},
      {"Dwarf", "mistrust"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "mistrust"},
      {"Wild Elf", "friendly"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "friendly"},
      {"Catman", "neutral"},
      {"Ratigan", "neutral"},
      {"Mermen", "mistrust"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Goblin"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "friendly"},
      {"Orc", "neutral"},
      {"Trorc", "neutral"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "neutral"},
      {"Mermen", "hate"},
      {"Harepon", "mistrust"},
      {"Locustin", "mistrust"},
      {"Lizardman", "mistrust"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Orc"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "neutral"},
      {"Orc", "friendly"},
      {"Trorc", "neutral"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "neutral"},
      {"Mermen", "hate"},
      {"Harepon", "mistrust"},
      {"Locustin", "mistrust"},
      {"Lizardman", "mistrust"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Trorc"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "neutral"},
      {"Orc", "friendly"},
      {"Trorc", "neutral"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "neutral"},
      {"Mermen", "hate"},
      {"Harepon", "mistrust"},
      {"Locustin", "mistrust"},
      {"Lizardman", "mistrust"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Owlman"] = {    
      {"Human", "mistrust"},
      {"Half Elf", "neutral"},
      {"Norlander", "mistrust"},
      {"Nomad", "neutral"},
      {"Elf", "neutral"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "neutral"},
      {"Gnome", "neutral"},
      {"Dwarf", "neutral"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "neutral"},
      {"Wild Elf", "neutral"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "friendly"},
      {"Catman", "neutral"},
      {"Ratigan", "hate"},
      {"Mermen", "neutral"},
      {"Harepon", "hate"},
      {"Locustin", "neutral"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Catman"] = {    
      {"Human", "mistrust"},
      {"Half Elf", "neutral"},
      {"Norlander", "mistrust"},
      {"Nomad", "neutral"},
      {"Elf", "neutral"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "neutral"},
      {"Gnome", "neutral"},
      {"Dwarf", "neutral"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "neutral"},
      {"Wild Elf", "neutral"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "friendly"},
      {"Catman", "neutral"},
      {"Ratigan", "hate"},
      {"Mermen", "neutral"},
      {"Harepon", "hate"},
      {"Locustin", "neutral"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Ratigan"] = {    
      {"Human", "hate"},
      {"Half Elf", "mistrust"},
      {"Norlander", "hate"},
      {"Nomad", "mistrust"},
      {"Elf", "mistrust"},
      {"Dark Elf", "hate"},
      {"High Elf", "hate"},
      {"Gnome", "mistrust"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "neutral"},
      {"Wild Elf", "hate"},
      {"Goblin", "mistrust"},
      {"Orc", "mistrust"},
      {"Trorc", "hate"},
      {"Owlman", "mistrust"},
      {"Catman", "hate"},
      {"Ratigan", "friendly"},
      {"Mermen", "hate"},
      {"Harepon", "hate"},
      {"Locustin", "neutral"},
      {"Lizardman", "neutral"},
      {"Naga", "neutral"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Mermen"] = {    
      {"Human", "mistrust"},
      {"Half Elf", "mistrust"},
      {"Norlander", "hate"},
      {"Nomad", "mistrust"},
      {"Elf", "mistrust"},
      {"Dark Elf", "hate"},
      {"High Elf", "mistrust"},
      {"Gnome", "neutral"},
      {"Dwarf", "mistrust"},
      {"Abyss Dwarf", "mistrust"},
      {"Topside Dwarf", "neutral"},
      {"Wild Elf", "mistrust"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "friendly"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "neutral"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
   ["Harepon"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "hate"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "mistrust"},
      {"Harepon", "friendly"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
   },
    ["Locustin"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "hate"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "hate"},
      {"Harepon", "mistrust"},
      {"Locustin", "friendly"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
    },
    ["Lizardman"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "hate"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "mistrust"},
      {"Orc", "mistrust"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "hate"},
      {"Harepon", "hate"},
      {"Locustin", "mistrust"},
      {"Lizardman", "friendly"},
      {"Naga", "friendly"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
    },
    ["Naga"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "hate"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "mistrust"},
      {"Orc", "mistrust"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "hate"},
      {"Harepon", "hate"},
      {"Locustin", "mistrust"},
      {"Lizardman", "friendly"},
      {"Naga", "friendly"},
      {"Skeleton", "hate"},
      {"Ghoul", "hate"},
      {"Zombie", "hate"}
    },
    ["Skeleton"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "hate"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "friendly"},
      {"Ghoul", "friendly"},
      {"Zombie", "friendly"}
    },
    ["Ghoul"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "hate"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "friendly"},
      {"Ghoul", "friendly"},
      {"Zombie", "friendly"}
    },
    ["Zombie"] = {    
      {"Human", "hate"},
      {"Half Elf", "hate"},
      {"Norlander", "hate"},
      {"Nomad", "hate"},
      {"Elf", "hate"},
      {"Dark Elf", "mistrust"},
      {"High Elf", "hate"},
      {"Gnome", "hate"},
      {"Dwarf", "hate"},
      {"Abyss Dwarf", "hate"},
      {"Topside Dwarf", "hate"},
      {"Wild Elf", "hate"},
      {"Goblin", "hate"},
      {"Orc", "hate"},
      {"Trorc", "hate"},
      {"Owlman", "hate"},
      {"Catman", "hate"},
      {"Ratigan", "hate"},
      {"Mermen", "hate"},
      {"Harepon", "hate"},
      {"Locustin", "hate"},
      {"Lizardman", "hate"},
      {"Naga", "hate"},
      {"Skeleton", "friendly"},
      {"Ghoul", "friendly"},
      {"Zombie", "friendly"}
   }
}

--factions[npc_map[y][x].a_type][iterator][disosition]
function get_faction_disp(playertype, npctype)
   for i, v in ipairs(factions[npctype]) do
      if factions[npctype][i][1] == playertype then
	 return factions[npctype][i][2]
      end
   end
   return "not found(neutral)" --assuming we didnt find the faction.
end
